### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by Florian-S-A-W** [pancakeswap/smart-router-example#4]
The project is currently not usable as [Typescript 5 is incompatible with react-scripts](https://github.com/facebook/create-react-app/issues/13080).
Running `npm install` fails with multiple errors.

**Comment by Florian-S-A-W** [comment]
I created a PR to fix this by adding overrides as suggested in the Issue linked. The app works without issues after that.
@chefjackson

**Comment by chefjackson** [comment]
Thanks for the help
